mozilla-services/loop-server

- loop/storage/redis.js
- loop/storage/redis_migration.js
- test/redis_migration_test.js
- test/storage_test.js
Based on #266
https://bugzilla.mozilla.org/show_bug.cgi?id=1100903
> Bug 1100903 — Put redis multi everywhere.

- loadtests/loadtest/rooms.py
- loop/storage/redis.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1111655
> Bug 1111655 — Update loadtest with the room owner guarenteed seat.

- loop/middlewares.js
- loop/routes/rooms.js
- test/middlewares_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1112379
> Bug 1112379 — Log number of room participants in metrics

- loop/index.js
- tools/send_sentry.js
* Send message on startup
* Add small CLI tool to send on demand
https://bugzilla.mozilla.org/show_bug.cgi?id=1098241
>  Bug 1098241 — Send message to Sentry on startup

- config/loadtest.json
- loop/config.js
- loop/index.js
- loop/logger.js
- loop/middlewares.js
- loop/websockets.js
- package.json
- test/functional_test.js
- test/middlewares_test.js
- test/websockets_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1080133
> Bug 1080133 — From winston with logrotate to mozlog on stdout.

- loop/routes/rooms.js
- loop/storage/redis.js
- loop/storage/redis_migration.js
- test/rooms_test.js
- test/storage_test.js
First attempt of handling this.
I wonder how we want to handle errors.
https://bugzilla.mozilla.org/show_bug.cgi?id=1106562
> Bug 1106562 — PATCH /rooms to delete multiple rooms.

- tools/fxa_impacted.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1111579
> Bug 1111579 — Remove keys impacted by the bug.

- redis_usage.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1067401
> Bug 1067401 — Redis Usage estimate script.

- loop/routes/rooms.js
- loop/tokbox.js
- test/rooms_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1094852
> Bug 1094852 — Handle Rooms Channel parameter.

- loop/auth.js
- loop/storage/redis.js
- test/auth_test.js
- test/index_test.js
- test/storage_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1118233
> Bug 1118233 — Set an expiration for oauth.token and heartbeat.

- loop/auth.js
- loop/routes/calls.js
- loop/routes/fxa-oauth.js
- test/functional_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1119855
> Bug 1119855 — Treat user identifier as case-insensitive.

- config/test.json
- loop/index.js
- loop/notifications.js
- loop/pubsub.js
- loop/routes/rooms.js
- loop/storage/redis.js
- test/rooms_test.js
- test/storage_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1093569
> Bug 1093569 — Add notifications on participant leave

- CHANGELOG
- package.json
https://cloud-services-fr.hackpad.com/Loop-release-schedule-50doMx1GA5n
> Update the changelog for 0.15 release.

- test/functional_test.js
- test/tools_test.js
- tools/get_expiration_estimate.js
- tools/migrate_1121403_roomparticipants.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1121403
> Bug 1121403 — Migration script for room participants

- loop/storage/redis_migration.js
- test/tools_test.js
- tools/migrate_redis.js
- tools/move_redis_data.js
> Bug 1023396 — Add a redis migration script.

- loop/storage/redis.js
- test/storage_test.js
> touchRoomData should ignore unexisting rooms.

- CHANGELOG
- package.json
> Tag 0.15.3

- loop/index.js
- loop/routes/calls.js
- loop/routes/rooms.js
- loop/simplepush.js
- loop/utils.js
- test/simplepush_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1127116
> Bug 1127116 - Monitor simple push calls.

- loop/config.js
- loop/index.js
- loop/newrelic.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1126889 r? @Natim
> Bug 1126889 - Add performance monitoring

- CHANGELOG
- package.json
> Release 0.15.5

- loop/config.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1133974
> Set the redis default in the configuration

- README.md
Also improve flow of headdings in the readme
> make headings have better grammer

- test/tools_test.js
- tools/get_tokbox_sessionid_for_room_token.js
> Add a test and use forEach.

- loop/pubsub.js
- loop/storage/redis.js
- loop/storage/redis_migration.js
> Default to localhost and 6379

- loop/middlewares.js
- loop/routes/rooms.js
- loop/routes/validators.js
- loop/storage/redis.js
- test/middlewares_test.js
- test/rooms_test.js
- test/storage_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1134884
> Bug 1134884 — Log current roomConnectionId for GET and POST /rooms/:token.

- loadtests/Makefile
- loadtests/loadtest/__init__.py
- loadtests/loadtest/calls.py
- loadtests/loadtest/rooms.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1102194
> Let precise the SIMPLE_PUSH_URL when running the loadtest

- test/tools_test.js
- tools/get_number_fxa_users.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1125597
> Bug 1125597 — Command to count number of FxA users

- loop/middlewares.js
- loop/routes/rooms.js
- test/middlewares_test.js
- test/rooms_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1134886
> Bug 1134886 — Log sessionId and sessionToken when available.

- loop/middlewares.js
- loop/routes/rooms.js
- test/middlewares_test.js
- test/rooms_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1137883
> Bug 1137883 — Log the roomToken on room creation.

- loop/routes/rooms.js
- test/rooms_test.js
Based on #309.
https://bugzilla.mozilla.org/show_bug.cgi?id=1137886
> Bug 1137886 — Log the number of participants for all POST /rooms/:token actions

- loop/auth.js
- loop/constants.js
- loop/middlewares.js
- test/rooms_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1140181
> Bug 1140181 — Add the user type to the request logs.

- loop/constants.js
- loop/middlewares.js
- loop/routes/rooms.js
- loop/routes/validators.js
- test/middlewares_test.js
- test/rooms_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1137849
> log messages should include all of the reported fields (event, state, connections, sendStreams, and recvStreams). These messages also need to include room participant count (the "participants" field in the current logs) and roomConnectionId.
> Bug 1137849 — Handle status action

- CHANGELOG
- loop/routes/home.js
- loop/storage/redis.js
- loop/storage/redis_migration.js
- test/functional_test.js
- test/storage_test.js
> Backport hotfixes

- CHANGELOG
- package.json
> Release 0.16.0

- loop/constants.js
- loop/routes/validators.js
- test/rooms_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1144851
> Bug 1144851 — Get rid of status validation

- CHANGELOG
- package.json
> Prepare 0.17.0

- loop/filestorage/aws.js
- loop/index.js
r? @Natim @leplatrem @deanwilson
> use the stack env in the bucket name

- CHANGELOG
- package.json
> Prepare 1.7.2 release.

- CHANGELOG
- loop/filestorage/aws.js
- loop/filestorage/filesystem.js
- loop/simplepush.js
- loop/tokbox.js
- package.json
- test/simplepush_test.js
> Fix AWS Bucket Name configuration and prepare 0.17.3 release.

- loadtests/loadtest/rooms.py
> Test room with context in loadtest.

- loop/routes/rooms.js
- test/rooms_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1169373
> Bug 1169373 — Log roomConnectionId on /rooms/:roomToken status update calls.

- loop/tokbox.js
- test/tokbox_test.js
> Add a statsd count for tokbox calls

- loop/auth.js
- loop/index.js
- loop/routes/call-url.js
- loop/routes/home.js
- loop/simplepush.js
- test/functional_test.js
- test/fxa_oauth_tests.js
- test/rooms_test.js
- test/simplepush_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1182762
> Bug 1182762 — Add SimplePush statsd counters.

- loadtests/Makefile
- loop/fxa.js
- test/fxa_test.js
> Handle error on FxA verifier side.

- loop/routes/home.js
- test/functional_test.js
> Add an heartbeat for the FxA verifier.

- CHANGELOG
- package.json
r? @ametaireau 
Should we wait on the verifier in the heartbeat?
> Prepare 0.18.0 release.

- loadtests/loadtest/__init__.py
- loadtests/loadtest/calls.py
Not sure how that passed review.
> pep8ify loadtesting code

- loadtests/Makefile
> Add missing dependency that is causing loads to fail

- CHANGELOG
- loop/routes/home.js
- package.json
- test/functional_test.js
> Fix FxA status URL

- loadtests/Makefile
- loadtests/config/megabench.ini
- loadtests/config/smoke.ini
> Fix loadtests v2

- loadtests/Makefile
- loadtests/loadtest/__init__.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1198142
> Add a smoke test that validates the heartbeat endpoint.

- config/loadtest.json
- loop/routes/rooms.js
- test/rooms_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1180140
> Bug 1180140 — A user should be able to rejoin with the same session.

- loop/routes/home.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1198141
> Bug 1198141 — Log an error if the heartbeat fails.

- loadtests/Makefile
> Fix loadtest Makefile

- loop/routes/home.js
- test/functional_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1253257
> Add a new __lbhealthcheck__ endpoint.
